Spotify:
  user: xxxxxxxxxxxxxx
  pass: xxxxxxxxxxxxxx

Playlists:

  Globals:
    - xxxxxxxxxxxxxxxx

  Users:
  
    user1:
      name: name
      playlists:
        - xxxxxxxxxxxx
        - xxxxxxxxxxx

Links:
  db: ./path/to/file
  plist: ./path/to/folder
  groupplaylist: ./path/to/file # Leave blank if in plist folder
  userplaylist: ./path/to/file # Leave blank if in plist folder